### ISSUE TITLE
Syntax error with latest build

### ISSUE THREAD

**Issue by wtbutler** [5etools-mirror-1/5etools-mirror-1.github.io#65]
Is this a bug or a feature request: Bug

Issue: SyntaxError when attempting to build project

Page(s) affected: node/clean-jsons.js

Reproduction steps:
Download `.tar.gz` release of 1.170.0 on linux (debian) and attempt to build

Additional information: I might have set up npm wrong, but I couldn't figure out how.

```
> 5etools@1.170.0 build
> npm run clean-jsons && npm run gen && npm run build:css && npm run build:sw:prod


> 5etools@1.170.0 clean-jsons
> node node/clean-jsons.js

/home/<user>/dev/5e-tools-repo/5etools-mirror-1.github.io-1.170.0/js/utils.js:470
	getEntitySource (it) { return it.source || it.inherits?.source; },
	                                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/<user>/dev/5e-tools-repo/5etools-mirror-1.github.io-1.170.0/node/clean-jsons.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /home/<user>/dev/5e-tools-repo/5etools-mirror-1.github.io-1.170.0
npm ERR! command failed
npm ERR! command sh -c node node/clean-jsons.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<user>/.npm/_logs/2022-12-01T16_12_14_039Z-debug.log
npm ERR! code 1
npm ERR! path /home/<user>/dev/5e-tools-repo/5etools-mirror-1.github.io-1.170.0
npm ERR! command failed
npm ERR! command sh -c npm run clean-jsons && npm run gen && npm run build:css && npm run build:sw:prod

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<user>/.npm/_logs/2022-12-01T16_12_14_782Z-debug.log
```

Browser (Chromium, Firefox, Edge, etc): couldn't get to a browser

Platform (Windows, iOS, Android, etc): linux (debian)

**Comment by TheGiddyLimit** [comment]
Update your Node.js

**Comment by wtbutler** [comment]
Thank you!
